spring:
  application:
    name: notificacao
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            auth: true
            starttls:
              enable: true
              connectiontimeout: 5000
              timeout: 3000
              writetimeout: 5000

  thymeleaf:
    enable: true

envio:
  email:
    remetente: 'marcelojacferreiradev@gmail.com'
    nomeRemetente: 'javanauta'

server:
  port: 8083